version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build Base Image
          command: docker build -t larasurf_base .
      - run:
          name: Build Test Image
          command: docker build -t larasurf_ci .circleci/
      - run:
          name: Run Tests
          command: |
            docker run --rm --entrypoint bash larasurf_ci -c "
            set -e
            cp .env.example .env
            ./vendor/bin/phpunit
            "

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
